apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd-image-updater
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-image-updater
        targetRevision: 0.12.0
        helm:
            valueFiles:
                - values-argocd-image-updater.yaml # repo 내부 값 사용
        path: . # repo root를 기반으로 value 파일을 찾음
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
