apiVersion: v1
kind: Secret
metadata:
    name: repo-kbsp-argocd-v3
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    url: git@github.com:ddcn4-1/kbsp-argocd-v3.git
    sshKeySecret: argocd-image-updater-sshkey
type: Opaque
