apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd-image-updater
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argocd-image-updater
        targetRevision: 1.0.1
        helm:
            releaseName: argocd-image-updater
            valueFiles:
                - values-argocd-image-updater.yaml # repo root에 있는 values 파일
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
